# Generated by Django 5.2.16 on 2026-07-21 05:41

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0003_sourceimport_digest_version_unique'),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagedCredential',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('provider', models.CharField(choices=[('gsc', 'Google Search Console'), ('ga4', 'Google Analytics 4'), ('semrush', 'SEMrush'), ('pagespeed', 'PageSpeed Insights'), ('s3', 'S3-compatible storage')], max_length=40, unique=True)),
                ('encrypted_credentials', models.TextField(blank=True)),
                ('encryption_key_id', models.CharField(blank=True, max_length=80)),
                ('credential_hint', models.CharField(blank=True, max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='managed_credentials', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ('provider',),
            },
        ),
    ]
