# Generated by Django 5.2.16 on 2026-07-21 07:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('domain', '0004_managedcredential'),
    ]

    operations = [
        migrations.CreateModel(
            name='PackageArchive',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('filename', models.CharField(max_length=255)),
                ('media_type', models.CharField(default='application/zip', max_length=120)),
                ('sha256', models.CharField(db_index=True, max_length=64)),
                ('size_bytes', models.PositiveBigIntegerField(default=0)),
                ('data', models.BinaryField()),
                ('artifact', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='db_archive', to='domain.artifact')),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='package_archives', to='domain.auditrun')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
